<a href="https://colab.research.google.com/github/shulaxshan/Linear-Regression/blob/main/Fish_weight_prediction_Polynominal_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# Import libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Import dataset

In [ ]:
dataset = pd.read_csv('/content/drive/MyDrive/My Online Training/Python/Udamey/Machine Learning A-Z™: Hands-On Python & R In Data Science/Part 2 - Regression/Polynomial Regression/Fish.csv')
X = dataset.iloc[:,[0,2,3,4,5,6]].values
y = dataset.iloc[:, 1].values


In [ ]:
dataset

Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...     ...      ...      ...      ...      ...     ...
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

#Encoding the Independent Variable

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])],remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 30.0 11.52 4.02]
 [1.0 0.0 0.0 ... 31.2 12.48 4.3056]
 [1.0 0.0 0.0 ... 31.1 12.3778 4.6961]
 ...
 [0.0 0.0 0.0 ... 13.8 2.277 1.2558]
 [0.0 0.0 0.0 ... 15.2 2.8728 2.0672]
 [0.0 0.0 0.0 ... 16.2 2.9322 1.8792]]


#Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

#Linear Regression

##Training the Multiple Linear Regression model on the Training set

In [ ]:
from sklearn.linear_model import LinearRegression
regression = LinearRegression()
regression.fit(X_train,y_train)

LinearRegression()

##Model Accouracy - Multiple Linear Regression


In [ ]:
from numpy.core.multiarray import concatenate
y_pred = regression.predict(X_test)
np.set_printoptions(precision=2)
print(y_pred)
print(concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[ 7.87e+02  1.07e+02  5.46e+02  1.94e+02  7.07e+01  6.05e+02  1.23e+02
  4.87e+02  7.08e+01  2.43e+02  1.75e+02  2.16e+02 -1.85e+02  3.71e+02
  7.12e+02  1.89e+02  1.83e+02  5.36e+02  4.68e+02  3.08e+02 -6.22e-01
 -1.71e+02  2.50e+02  4.95e+02  1.47e+02  8.34e+02  5.85e+02 -8.35e+01
  1.28e+03  1.99e+02  1.03e+03  3.67e+02]
[[ 7.87e+02  1.00e+03]
 [ 1.07e+02  1.20e+02]
 [ 5.46e+02  6.00e+02]
 [ 1.94e+02  1.30e+02]
 [ 7.07e+01  8.50e+01]
 [ 6.05e+02  6.50e+02]
 [ 1.23e+02  1.45e+02]
 [ 4.87e+02  5.00e+02]
 [ 7.08e+01  0.00e+00]
 [ 2.43e+02  1.45e+02]
 [ 1.75e+02  1.35e+02]
 [ 2.16e+02  1.50e+02]
 [-1.85e+02  3.20e+01]
 [ 3.71e+02  2.50e+02]
 [ 7.12e+02  8.00e+02]
 [ 1.89e+02  1.10e+02]
 [ 1.83e+02  1.40e+02]
 [ 5.36e+02  3.90e+02]
 [ 4.68e+02  3.20e+02]
 [ 3.08e+02  1.97e+02]
 [-6.22e-01  9.80e+00]
 [-1.71e+02  4.00e+01]
 [ 2.50e+02  1.80e+02]
 [ 4.95e+02  4.50e+02]
 [ 1.47e+02  1.25e+02]
 [ 8.34e+02  9.55e+02]
 [ 5.85e+02  7.00e+02]
 [-8.35e+01  6.70e+00]
 [ 1.28e+03  1.55e+03]
 [ 1.99

In [ ]:
from sklearn import metrics

print("Training set score: {:.7f}".format(regression.score(X_train, y_train)))
print("Test set score: {:.7f}".format(regression.score(X_test, y_test)))
print("RMSE: {:.7f}".format(np.sqrt(metrics.mean_squared_error(y_test, y_pred))))

Training set score: 0.9403384
Test set score: 0.9109343
RMSE: 109.6908036


#Polynominal Linear Regression

##Training the Polynomial Regression model on the whole dataset

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree = 2)
X_poly = poly_reg.fit_transform(X_train)
lin_reg2 = LinearRegression()
lin_reg2.fit(X_poly,y_train)

LinearRegression()

##Model Accuracy

In [ ]:
from sklearn import metrics
y_poly_pred = lin_reg2.predict(poly_reg.fit_transform(X_test))
print("Training set score: {:.7f}".format(lin_reg2.score(poly_reg.fit_transform(X_train), y_train)))
print("Test set score: {:.7f}".format(lin_reg2.score(poly_reg.fit_transform(X_test), y_test)))
print("RMSE: {:.7f}".format(np.sqrt(metrics.mean_squared_error(y_test, y_poly_pred))))

Training set score: 0.9802941
Test set score: 0.9770127
RMSE: 55.7261222


#Conclusion
#####Polynominal Linear regression has been performed well compared with Linear regression model. RMSE value very less compared with linear regression model.
